---
- hosts: host
  become: true
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding.
      net.ipv4.ip_forward: 1
  roles:
    - { role: ohr486.elixir, erlang_version: 26.0.1, elixir_version: v1.15.4, erl_configure_options: '--enable-hipe --enable-smp-support' }
